### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zavarana-uhorka** [microsoft/openjdk#78] opened 2021-06-22 09:31 UTC
everytime i alttab minecraft to obs studio it just crashes idk whats the problem please help here is the crash log https://pastebin.com/27A50Z8c

**Comment by brstaffoMS** [comment] 2021-06-22 15:29
Hi @zavarana-uhorka! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look at this issue. Thanks!

**Comment by karianna** [comment] 2021-06-23 09:16
Likely duplicate of #69

**Comment by karianna** [comment] 2021-06-23 09:17
Please also see https://bugs.mojang.com/browse/MC-229195

**Closed** 2021-06-23 09:17 UTC
Labels: Minecraft, Reported Upstream, duplicate
