### ISSUE TITLE
fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by Arsenal125** [microsoft/openjdk#337] opened 2022-11-09 16:07 UTC
# JRE version: OpenJDK Runtime Environment Microsoft-6841604 (17.0.5+8) (build 17.0.5+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-6841604 (17.0.5+8-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [DarkBoatAPI.dll+0x21aff]

![vaizdas_2022-11-09_180727943](https://user-images.githubusercontent.com/117846745/200880825-b66f2beb-0f30-4be6-946f-a768a737044e.png)

**Comment by karianna** [comment] 2022-11-10 00:26
@Arsenal125 

Thank you for the report!
Is this a modified version of Minecraft? The following was detected in your crash report:
```
DarkBoatAPI
```
If so, please report this crash to the mod creator. If you can also reproduce this crash without having any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).

**Comment by mosslog** [comment] 2022-11-28 04:50
i got a similar or the same crass   minecraft 1.19.2  forge 43.1.57  no mods (effectively just minecraft and a mod loader but no mods)  last line of minecraft log  [error occurred during error reporting (), id 0xc0000005, EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbc7fdafc9]
[hs_err_pid1868.log](https://github.com/microsoft/openjdk/files/10100554/hs_err_pid1868.log)

**Comment by karianna** [comment] 2022-12-04 07:40
There have been a host of recent crash reports due to a bug in the NVidia drivers.  For a number of folks, downgrading to the previous version of that driver resolves the issue.

**Comment by the-playz** [comment] 2022-12-09 10:00
I cant load 1.19.3 because of this, but i did go to 1.19.2 and i can load. do yall have any idea then this might get resolved?

**Comment by karianna** [comment] 2022-12-12 08:34
@Playz07 - Not sure sorry. You may want to try the Mojang bug tracker / forums and see if they have worked out a resolution with NVidia.

**Comment by Frontear** [comment] 2022-12-18 00:00
Partially unrelated but theres a similar issue with an amd dll for their gpu drivers. I reported the issue and it was instantly closed as an MC issue (unfortunately I cant report to Mojang since its a modded environment and it will also be auto rejected).

**Comment by ImKhione** [comment] 2022-12-23 23:08
I'm having this issues currently as well, I've tried updating drivers, rolling back drivers, uninstalling/reinstalling and have gotten no where. I can load up 1.17 no problem but if i try to play 1.18 or 1.19 it gives me this error every time without fail I don't even make it to the point of seeing the mojang loading screen

**Comment by karianna** [comment] 2022-12-26 21:53
We've also seen reports that fix issues for AMD:

If you are running on AMD...

```
Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"
```

**Comment by ImKhione** [comment] 2022-12-26 22:23
I’m not on AMD I’m on 13th Gen Intel

**Comment by karianna** [comment] 2022-12-26 22:34
@ImKhione what graphics card and driver do you use?

**Comment by ImKhione** [comment] 2022-12-26 22:59
@karianna Nvidia 3070TI and the drivers I have installed released 12/8/22

**Comment by karianna** [comment] 2022-12-26 23:26
@ImKhione I assume you're using an unmodded version ?

**Comment by ImKhione** [comment] 2022-12-26 23:39
@karianna yes trying to play just the big standard vanilla version of anythin 1.18 or newer results in the crash, 1.17 loads just fine

**Comment by karianna** [comment] 2022-12-27 01:36
@ImKhione - 
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.

**Comment by ImKhione** [comment] 2022-12-27 02:07
@karianna i just tried it again for the first time since yesterday and it launched no problem… I have no words

**Comment by karianna** [comment] 2022-12-27 03:50
Plenty changes (driver versions, Minecraft launcher etc), glad to hear it is working.

**Closed by karianna** 2022-12-27 03:50 UTC
Labels: Waiting on OP, Minecraft
