### ISSUE TITLE
Minecraft 地圖方塊出問替

### ISSUE THREAD

**Issue by 3016052** [microsoft/openjdk#70] opened 2021-06-16 05:11 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by karianna** [comment] 2021-06-16 10:37
Looks like a duplicate of #71

**Closed by karianna** 2021-06-16 10:37 UTC
Labels: duplicate, invalid
