### ISSUE TITLE
the exception runs in the  ForkJoinPool$WorkQueue.helpComplete

### ISSUE THREAD

**Issue by a364176773** [microsoft/openjdk#308] opened 2022-08-19 03:58 UTC
**Describe the bug**
Threads are blocked here, and CPU ge is 100%
**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:
alpine-3.12.9
**MSFT Build of OpenJDK Version:**

The output from `java --version`
17+35
**To Reproduce:**
I can only say that this operation is a probability
```
        groupIds.parallelStream().forEach(groupId -> {
           handle.....
        });
```
**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.
![image](https://user-images.githubusercontent.com/19943636/185539643-fdb5146a-6c7d-48d6-9a6e-4036a0145293.png)
```
"pool-13-thread-1" #39 prio=5 os_prio=0 cpu=29010095.62ms elapsed=58895.52s tid=0x0000562084f94700 nid=0x7b runnable  [0x00007efeb42ab000]
   java.lang.Thread.State: RUNNABLE
        at java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(java.base@17/ForkJoinPool.java:1228)
        at java.util.concurrent.ForkJoinPool.helpComplete(java.base@17/ForkJoinPool.java:1915)
        at java.util.concurrent.ForkJoinTask.awaitDone(java.base@17/ForkJoinTask.java:433)
        at java.util.concurrent.ForkJoinTask.invoke(java.base@17/ForkJoinTask.java:687)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(java.base@17/ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(java.base@17/ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(java.base@17/AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(java.base@17/ReferencePipeline.java:596)
        at java.util.stream.ReferencePipeline$Head.forEach(java.base@17/ReferencePipeline.java:765)
     .......
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17/Executors.java:539)
        at java.util.concurrent.FutureTask.runAndReset(java.base@17/FutureTask.java:305)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@17/ScheduledThreadPoolExecutor.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17/Thread.java:833)

```

**Additional context**
My container CPU has only 1 c and memory 1g

**Comment by karianna** [comment] 2022-08-22 13:06
This is a duplicate of the Eclipse Temurin bug report (this is not for an MSFT binary)

**Closed by karianna** 2022-08-22 13:06 UTC
